### ISSUE TITLE
where to order the PCB?

### ISSUE THREAD

**Issue by LuisMarek** [hierle/letterbox-sensor#9]
Hello,

is it possible to order the PCB somewhere or or must everyone find a company themselves that can make this PCB individually? The rest of the parts is not a problem, but the PCB is here probably the obstacle, so at least for me. 

Thanks & best regards
Luis

**Comment by hierle** [comment]
Hi Luis,

may I ask for your mailing address? ;)

Cheers
Alex
***@***.***>

**Comment by hierle** [comment]
Hi,

PCBs are not for sale ... but if you drop me a note with your mailing address (e.g. via contact on infotiger.com),  I might have a spare PCB laying around :)

Cheers
Alex
